defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: 

# note we share same db for dev and production!
development:
  <<: *defaults
  database: mezmurs_development

test:
  <<: *defaults
  database: mezmurs_test

production:
  <<: *defaults
  database: mezmurs_production
